max_iteration: 4
img_enable: 1
lidar_enable: 1

point_filter_num: 4
filter_size_surf: 0.2
filter_size_map: 0.4

common:
    lid_topic:  /livox/lidar
    imu_topic:  /livox/imu
    img_topic:  /camera/image_raw

preprocess:
    lidar_type: 1 # Livox Avia LiDAR
    scan_line: 6
    blind: 0.5 # blind x m disable
    timestamp_unit: 3
    align_timestamp_en: false

mapping:
    gyr_cov: 0.1
    acc_cov: 0.1
    b_gyr_cov: 0.0001
    b_acc_cov: 0.0001
    laser_point_cov: 0.001
    det_range: 450.0
    extrinsic_est_en: false
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
    Rcl: [0.0105053,-0.999944,0.000932287,
          0.00990412,-0.000828241,-0.999951,
          0.999896,0.010514,0.00989487,]
    Pcl: [0.00787518, -0.0382755, 0.0178531]

camera:
    debug: 0
    visual_point_cov: 500
    cam_width: 1280
    cam_height: 1024
    cam_fx: 1294.9
    cam_fy: 1294.4
    cam_cx: 625.5857
    cam_cy: 519.1991
    grid_size: 40
    patch_size: 8

pcd_save:
    pcd_save_en: true

std:
    # pre process
    ds_size: 0.1
    maximum_corner_num: 100
    # key points
    plane_detection_thre: 0.01
    plane_merge_normal_thre: 0.2
    voxel_size: 1.0
    voxel_init_num: 10
    proj_image_resolution: 0.1
    proj_dis_min: 0
    proj_dis_max: 5
    corner_thre: 1
    # std descriptor
    descriptor_near_num: 50
    descriptor_min_len: 2
    descriptor_max_len: 30
    non_max_suppression_radius: 0.1
    std_side_resolution: 0.2

loop:
    # pcd_save_en: true
    # keyframe_dist_thresh: 1.0
    # keyframe_time_thresh: 30.0
    # max_loop_distance: -1.0
    # skip_near_num: 10
    # candidate_num: 50

    # cdesc_verify_en: true
    # cdesc_diff_thresh: 0.8
    # vertex_diff_thresh: 0.5
    # side_length_thresh: 0.01
    # planegeo_normal_thresh: 0.2
    # planegeo_dis_thresh: 0.5
    # planegeo_icp_thresh: 0.4

    # pcd_save_en: true
    # keyframe_dist_thresh: 1.0
    # keyframe_time_thresh: 60.0
    # max_loop_distance: -1
    # skip_near_num: 10
    # candidate_num: 50

    # cdesc_verify_en: false
    # cdesc_diff_thresh: 0.8
    # vertex_diff_thresh: 0.5
    # side_length_thresh: 0.01
    # planegeo_normal_thresh: 0.2
    # planegeo_dis_thresh: 0.5
    # planegeo_icp_thresh: 0.4

    pcd_save_en: true
    keyframe_dist_thresh: 1.0
    keyframe_time_thresh: 60.0
    max_loop_distance: -1
    skip_near_num: 50
    candidate_num: 10

    cdesc_verify_en: true
    cdesc_diff_thresh: 0.8
    vertex_diff_thresh: 0.5
    side_length_thresh: 0.01
    planegeo_normal_thresh: 0.2
    planegeo_dis_thresh: 0.5
    planegeo_icp_thresh: 0.4